repository:
  default_branch: develop
  private: true
  allow_squash_merge: true
  allow_merge_commit: true
  allow_rebase_merge: true
  delete_branch_on_merge: true
  enable_automated_security_fixes: true
  enable_vulnerability_alerts: true

# See https://developer.github.com/v3/teams/#add-or-update-team-repository for available options
teams:
  - name: WebTeam
    permission: maintain

# https://developer.github.com/v3/repos/branches/#update-branch-protection
branches:
  - name: develop
    protection:
      required_pull_request_reviews:
        required_approving_review_count: 1
        require_code_owner_reviews: false
      required_status_checks: null
      enforce_admins: null
      restrictions: null

# Labels: define labels for Issues and Pull Requests
labels:
  - name: bug
    color: CC0000
    description: An issue with the system 🐛.

  - name: feature
    # If including a `#`, make sure to wrap it with quotes!
    color: '#336699'
    description: New functionality.

