name: Build Feature
# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the feature branch
  push:
    branches:
      - feature/**

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    # Add permissions to the authentication token
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: corretto

      - name: Compile with Maven
        run: |
          cd java
          mvn test
